services:
    mssql:
        container_name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          SA_PASSWORD: "senha123@"
          ACCEPT_EULA: "Y"
          MSSQL_PID: "Developer"
        ports:
          - "1433:1433"